### ISSUE TITLE
endpoint connect ignores connect target, and reuses target from the previous Busy attempt

### ISSUE THREAD

**Issue by jediller** [WASdev/lib.rtcomm.clientjs#33]
A user attempts to start a chat to a user, already in a chat. This fails with a reason code of Busy. The same user then attempts to start a chat with a different user, that is not busy. That chat session request times out. It appears the user specified in the connect request, in this case svt103.583819 is ignored. Instead the user that was previously called (svt101.583819) and found busy is reused.

14-12-23 11:57:32 session:failed[svt102.583819]; eventName: session:failed; endpoint: RtcommEndpoint[f03a95b2-f66b-427f-8a6b-df1895efeac7]; reason: Transaction 70 Timed out [381b14cd-bd8e-4fdf-cb9d-29d07821453b] after  5000: Tue Dec 23 2014 11:57:32 GMT-0500 (EST)
14-12-23 11:57:32 chat:disconnected[svt102.583819]; eventName: chat:disconnected; endpoint: RtcommEndpoint[f03a95b2-f66b-427f-8a6b-df1895efeac7]; partner: svt101.583819
14-12-23 11:57:27 chat:connected[svt102.583819]; eventName: chat:connected; endpoint: RtcommEndpoint[f03a95b2-f66b-427f-8a6b-df1895efeac7]; partner: svt101.583819
14-12-23 11:57:27 user: svt102.583819 attempts: rtcommEndpoint.connect(svt103.583819)

**Comment by swgraham** [comment]
This should be resolved in the release/v1.0.0-beta.9 branch.  Now resetting activeSession on failed.
