### ISSUE TITLE
Test fail to execute

### ISSUE THREAD

**Issue by jediller** [WASdev/lib.rtcomm.clientjs#39]
Following these instructions; and launching a browser

* Tests for the rtcomm clienjs project

As of 12/18/2014, these tests run using 'theintern.io'.

** Configure the tests

Access the file 'tests/support/testConfig.json':
```
{
   "mqttServers" : ["messagesight.demos.ibm.com:1883"],
   "managementTopicName" : "management",
   "rtcommTopicPath" : "/rtcomm/"
}
```

Change the contents of this file to match the configuration of your liberty server.

** Running the tests

1.  Setup the Prereqs:

```
# from the project directory lib.rtcomm.clientjs
# Install prereqs (one time only) via the package.json devDependencies
npm install -g grunt-cli
npm install
```

These tests can be run in two ways:

1.  Via a Browser:  With an http server pointing at the project directory, access the link http://localhost:<port>/node_modules/intern/client.html?config=tests/intern  via a Browser.  This will run the tests and display the results in the browser.

If you have node.js installed, you can quickly launch a local browser to test:

```
# Launch the server
node tests/support/server.js .
```
Now you should be able to access http://localhost:3000/node_modules/intern/client.html?config=tests/intern

The Browser console reported these errors

Error in parsing value for 'background-image'.  Declaration dropped. latest:60
Unknown property 'user-select'.  Declaration dropped. latest:76
Expected media feature name but found '-webkit-min-device-pixel-ratio'. latest:154
Expected media feature name but found '-o-min-device-pixel-ratio'. latest:156
Expected media feature name but found 'min-device-pixel-ratio'. latest:157
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. _error.js:2
Error in parsing value for 'transform'.  Declaration dropped. github2-a34ea5f36919335b720f812ba66ac87065665d8d6d759d6f237e7129ba34edb6.css:1
Error in parsing value for 'margin-top'.  Declaration dropped. github2-a34ea5f36919335b720f812ba66ac87065665d8d6d759d6f237e7129ba34edb6.css:1
Error in parsing value for 'vertical-align'.  Declaration dropped. github2-a34ea5f36919335b720f812ba66ac87065665d8d6d759d6f237e7129ba34edb6.css:1
Expected media feature name but found '-webkit-min-device-pixel-ratio'. github2-a34ea5f36919335b720f812ba66ac87065665d8d6d759d6f237e7129ba34edb6.css:1
Error in parsing value for 'background-image'.  Declaration dropped. github2-a34ea5f36919335b720f812ba66ac87065665d8d6d759d6f237e7129ba34edb6.css:1
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. github2-a34ea5f36919335b720f812ba66ac87065665d8d6d759d6f237e7129ba34edb6.css:1
Unknown property 'tab-size'.  Declaration dropped. github2-a34ea5f36919335b720f812ba66ac87065665d8d6d759d6f237e7129ba34edb6.css:1
Unknown property 'user-select'.  Declaration dropped. github2-a34ea5f36919335b720f812ba66ac87065665d8d6d759d6f237e7129ba34edb6.css:1
Error in parsing value for 'word-break'.  Declaration dropped. github2-a34ea5f36919335b720f812ba66ac87065665d8d6d759d6f237e7129ba34edb6.css:1
Missing closing ')' in negation pseudo-class '.'.  Ruleset ignored due to bad selector. github2-a34ea5f36919335b720f812ba66ac87065665d8d6d759d6f237e7129ba34edb6.css:1
Expected media feature name but found 'min-device-pixel-ratio'. github2-a34ea5f36919335b720f812ba66ac87065665d8d6d759d6f237e7129ba34edb6.css:1
Error in parsing value for 'cursor'.  Declaration dropped. github2-a34ea5f36919335b720f812ba66ac87065665d8d6d759d6f237e7129ba34edb6.css:1
Unknown pseudo-class or pseudo-element '-webkit-inner-spin-button'.  Ruleset ignored due to bad selector. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:1
Unknown pseudo-class or pseudo-element '-webkit-search-cancel-button'.  Ruleset ignored due to bad selector. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:1
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:1
Unknown pseudo-class or pseudo-element '-webkit-validation-bubble-message'.  Ruleset ignored due to bad selector. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:1
Unknown pseudo-class or pseudo-element '-webkit-validation-bubble-icon'.  Ruleset ignored due to bad selector. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:1
Unknown pseudo-class or pseudo-element '-webkit-validation-bubble-arrow'.  Ruleset ignored due to bad selector. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:1
Unknown property 'background-position-x'.  Declaration dropped. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:1
Unknown pseudo-class or pseudo-element '-webkit-outer-spin-button'.  Ruleset ignored due to bad selector. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:1
Error in parsing value for 'background-image'.  Declaration dropped. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:1
Unknown property 'user-select'.  Declaration dropped. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:1
Error in parsing value for 'width'.  Declaration dropped. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:1
Error in parsing value for 'word-break'.  Declaration dropped. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:1
Found invalid value for media feature. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:1
Expected color but found '#eee\9 '.  Expected end of value but found '#eee\9 '.  Error in parsing value for 'border-top'.  Declaration dropped. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:1
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:3
Unknown property 'user-select'.  Declaration dropped. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:3
Expected 'none' or URL but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:3
Unknown property '-moz-border-radius'.  Declaration dropped. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:3
Expected media feature name but found '-webkit-min-device-pixel-ratio'. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:3
Expected media feature name but found 'min-device-pixel-ratio'. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:3
Expected end of selector or a user action pseudo-class after pseudo-element but found ':'.  Ruleset ignored due to bad selector. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:3
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:3
Error in parsing value for 'background-image'.  Declaration dropped. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:3
Error in parsing value for 'word-break'.  Declaration dropped. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:3
Error in parsing value for 'position'.  Declaration dropped. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:3
Error in parsing value for 'display'.  Declaration dropped. github-5babf25e3161fe5231c33e09fef433d57ceb643fe0850efd515f6139e9a2419b.css:3
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create frameworks-9643b0378c6bcb216adcdaaaa703eed77aa239aaf1c2ae44cadb2fb5099ec172.js:34
"FATAL ERROR" console.js:32
Error: Failed to load module umd/rtcomm/util from /dist/umd/rtcomm/util.js (parent: unit/util/util.js) dojo.js:731
"Error: Failed to load module umd/rtcomm/util from /dist/umd/rtcomm/util.js (parent: unit/util/util.js)
  at injectUrl/handler  <node_modules/intern/node_modules/dojo/dojo.js:731:7>" util.js:625

Error: Failed to load module umd/rtcomm/connection from /dist/umd/rtcomm/connection.js (parent: functional/connection/MqttConnection.js) dojo.js:731
"FATAL ERROR" console.js:32
"Error: Failed to load module umd/rtcomm/connection from /dist/umd/rtcomm/connection.js (parent: functional/connection/MqttConnection.js)
  at injectUrl/handler  <node_modules/intern/node_modules/dojo/dojo.js:731:7>" util.js:625

"FATAL ERROR" console.js:32
"Error: Failed to load module umd/rtcomm from /dist/umd/rtcomm.js (parent: unit/EndpointProvider.js)
  at injectUrl/handler  <node_modules/intern/node_modules/dojo/dojo.js:731:7>" util.js:625

Error: Failed to load module umd/rtcomm from /dist/umd/rtcomm.js (parent: unit/EndpointProvider.js) dojo.js:731
POST https://www.google-analytics.com/r/collect [HTTP/1.1 200 OK 124ms]
GET https://github.com/login [HTTP/1.1 200 OK 397ms]
POST http://ocsp.digicert.com/ [HTTP/1.1 200 OK 47ms]
POST http://ocsp.digicert.com/ [HTTP/1.1 200 OK 59ms]
GET https://assets-cdn.github.com/assets/github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css [HTTP/1.1 200 OK 466ms]
GET https://assets-cdn.github.com/assets/github-df43b1353e973de5b95b33142ab31dd9a7e86649b0e2d09a2ce4f3ce6bb0d2a4.js [HTTP/1.1 200 OK 908ms]
Unknown pseudo-class or pseudo-element '-webkit-inner-spin-button'.  Ruleset ignored due to bad selector. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:1
Unknown pseudo-class or pseudo-element '-webkit-search-cancel-button'.  Ruleset ignored due to bad selector. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:1
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:1
Unknown pseudo-class or pseudo-element '-webkit-validation-bubble-message'.  Ruleset ignored due to bad selector. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:1
Unknown pseudo-class or pseudo-element '-webkit-validation-bubble-icon'.  Ruleset ignored due to bad selector. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:1
Unknown pseudo-class or pseudo-element '-webkit-validation-bubble-arrow'.  Ruleset ignored due to bad selector. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:1
Unknown property 'background-position-x'.  Declaration dropped. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:1
Unknown pseudo-class or pseudo-element '-webkit-outer-spin-button'.  Ruleset ignored due to bad selector. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:1
Error in parsing value for 'background-image'.  Declaration dropped. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:1
Unknown property 'user-select'.  Declaration dropped. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:1
Error in parsing value for 'width'.  Declaration dropped. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:1
Error in parsing value for 'word-break'.  Declaration dropped. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:1
Found invalid value for media feature. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:1
Expected color but found '#eee\9 '.  Expected end of value but found '#eee\9 '.  Error in parsing value for 'border-top'.  Declaration dropped. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:1
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:3
Unknown property 'user-select'.  Declaration dropped. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:3
Expected 'none' or URL but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:3
Unknown property '-moz-border-radius'.  Declaration dropped. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:3
Expected media feature name but found '-webkit-min-device-pixel-ratio'. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:3
Expected media feature name but found 'min-device-pixel-ratio'. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:3
Expected end of selector or a user action pseudo-class after pseudo-element but found ':'.  Ruleset ignored due to bad selector. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:3
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:3
Error in parsing value for 'background-image'.  Declaration dropped. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:3
Error in parsing value for 'word-break'.  Declaration dropped. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:3
Error in parsing value for 'position'.  Declaration dropped. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:3
Error in parsing value for 'display'.  Declaration dropped. github-554de21a71e1d82d8eb0c2e84b812ff1d19b151d6de024f3f4b02e60b2e40682.css:3
GET https://www.google-analytics.com/collect [HTTP/1.1 200 OK 34ms]
POST https://www.google-analytics.com/collect [HTTP/1.1 200 OK 48ms]
GET https://collector.githubapp.com/github/page_view [HTTP/1.1 200 OK 423ms]
POST https://github.com/_stats [HTTP/1.1 200 OK 37ms]
POST https://github.com/session [HTTP/1.1 200 OK 145ms]
GET https://www.google-analytics.com/collect [HTTP/1.1 200 OK 54ms]
POST https://www.google-analytics.com/collect [HTTP/1.1 200 OK 69ms]
GET https://collector.githubapp.com/github/page_view [HTTP/1.1 200 OK 64ms]
POST https://github.com/_stats [HTTP/1.1 200 OK 42ms]
TypeError: can't access dead object popup.xml:304
POST https://github.com/session [HTTP/1.1 200 OK 234ms]
GET https://www.google-analytics.com/collect [HTTP/1.1 200 OK 50ms]
POST https://www.google-analytics.com/collect [HTTP/1.1 200 OK 65ms]
GET https://collector.githubapp.com/github/page_view [HTTP/1.1 200 OK 54ms]
POST https://github.com/_stats [HTTP/1.1 200 OK 44ms]
GET https://github.com/password_reset [HTTP/1.1 200 OK 56ms]
GET https://www.google-analytics.com/collect [HTTP/1.1 200 OK 50ms]
POST https://www.google-analytics.com/collect [HTTP/1.1 200 OK 65ms]
GET https://collector.githubapp.com/github/page_view [HTTP/1.1 200 OK 53ms]
POST https://github.com/_stats [HTTP/1.1 200 OK 49ms]
POST https://github.com/password_reset [HTTP/1.1 200 OK 161ms]
GET https://www.google-analytics.com/collect [HTTP/1.1 200 OK 56ms]
POST https://www.google-analytics.com/collect [HTTP/1.1 200 OK 71ms]
GET https://collector.githubapp.com/github/page_view [HTTP/1.1 200 OK 54ms]
POST https://github.com/_stats [HTTP/1.1 200 OK 45ms]
POST https://safebrowsing.google.com/safebrowsing/downloads [HTTP/1.1 200 OK 156ms]
GET https://safebrowsing-cache.google.com/safebrowsing/rd/ChVnb29nLWJhZGJpbnVybC1zaGF2YXI4AEACSgwIARCA2QIYgtkCIAFKDAgAEOr2Ahju9gIgAQ [HTTP/1.1 200 OK 220ms]
GET https://safebrowsing-cache.google.com/safebrowsing/rd/ChNnb29nLW1hbHdhcmUtc2hhdmFyOABAAkoMCAEQ2vkJGN75CSABSgwIABCZwAoYncAKIAE [HTTP/1.1 200 OK 34ms]
GET https://safebrowsing-cache.google.com/safebrowsing/rd/ChFnb29nLXBoaXNoLXNoYXZhcjgAQAJKDAgBEIa-DBiJvgwgAUoMCAAQ0PQWGNT0FiAB [HTTP/1.1 200 OK 34ms]
GET https://github.com/login [HTTP/1.1 200 OK 210ms]
GET https://www.google-analytics.com/collect [HTTP/1.1 200 OK 181ms]
POST https://www.google-analytics.com/collect [HTTP/1.1 200 OK 206ms]
GET https://collector.githubapp.com/github/page_view [HTTP/1.1 200 OK 529ms]
POST https://github.com/_stats [HTTP/1.1 200 OK 52ms]
POST https://github.com/session [HTTP/1.1 302 Found 95ms]
GET https://github.com/ [HTTP/1.1 200 OK 102ms]
GET https://avatars3.githubusercontent.com/u/8375714 [HTTP/1.1 200 OK 1265ms]
GET https://assets-cdn.github.com/images/modules/dashboard/bootcamp/octocat_setup.png [HTTP/1.1 200 OK 278ms]
GET https://assets-cdn.github.com/images/modules/dashboard/bootcamp/octocat_repo.png [HTTP/1.1 200 OK 80ms]
GET https://assets-cdn.github.com/images/modules/dashboard/bootcamp/octocat_fork.png [HTTP/1.1 200 OK 657ms]
GET https://assets-cdn.github.com/images/modules/dashboard/bootcamp/octocat_collabocats.png [HTTP/1.1 200 OK 746ms]
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create frameworks-9643b0378c6bcb216adcdaaaa703eed77aa239aaf1c2ae44cadb2fb5099ec172.js:34
GET https://www.google-analytics.com/collect [HTTP/1.1 200 OK 439ms]
POST https://www.google-analytics.com/collect [HTTP/1.1 200 OK 495ms]
POST https://www.google-analytics.com/collect [HTTP/1.1 200 OK 498ms]
POST https://www.google-analytics.com/collect [HTTP/1.1 200 OK 496ms]
POST https://www.google-analytics.com/collect [HTTP/1.1 200 OK 494ms]
GET https://collector.githubapp.com/github/page_view [HTTP/1.1 200 OK 319ms]
POST https://github.com/_stats [HTTP/1.1 200 OK 47ms]
TypeError: can't access dead object popup.xml:304
POST https://www.google-analytics.com/collect [HTTP/1.1 200 OK 57ms]
GET https://github.com/WASdev/lib.rtcomm.clientjs [HTTP/1.1 200 OK 155ms]
GET https://avatars0.githubusercontent.com/u/8354609 [HTTP/1.1 304 Not Modified 591ms]
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create frameworks-9643b0378c6bcb216adcdaaaa703eed77aa239aaf1c2ae44cadb2fb5099ec172.js:34
GET https://github.com/WASdev/lib.rtcomm.clientjs/contributors_size [HTTP/1.1 200 OK 408ms]
GET https://github.com/WASdev/lib.rtcomm.clientjs/show_partial [HTTP/1.1 200 OK 645ms]
GET https://www.google-analytics.com/collect [HTTP/1.1 200 OK 59ms]
POST https://www.google-analytics.com/collect [HTTP/1.1 200 OK 72ms]
GET https://github.com/WASdev/lib.rtcomm.clientjs/issues/counts [HTTP/1.1 200 OK 638ms]
GET https://collector.githubapp.com/github/page_view [HTTP/1.1 200 OK 147ms]
POST https://github.com/_stats [HTTP/1.1 200 OK 49ms]
GET https://github.com/WASdev/lib.rtcomm.clientjs/issues [HTTP/1.1 200 OK 126ms]
Relative positioning of table rows and row groups is now supported. This site may need to be updated because it may depend on this feature having no effect. frameworks-9643b0378c6bcb216adcdaaaa703eed77aa239aaf1c2ae44cadb2fb5099ec172.js:82
GET https://assets-cdn.github.com/assets/spinners/octocat-spinner-128-338974454bb5c32803e82f601beb051d373744b024fe8742a76009700fd7e033.gif [HTTP/1.1 200 OK 84ms]
GET https://avatars3.githubusercontent.com/u/8354609 [HTTP/1.1 200 OK 63ms]
GET https://collector.githubapp.com/github/page_view [HTTP/1.1 200 OK 216ms]
GET https://www.google-analytics.com/collect [HTTP/1.1 200 OK 44ms]
POST https://www.google-analytics.com/collect [HTTP/1.1 200 OK 58ms]
POST https://github.com/_stats [HTTP/1.1 200 OK 50ms]
GET https://github.com/WASdev/lib.rtcomm.clientjs/issues/show_menu_content [HTTP/1.1 200 OK 59ms]
GET https://avatars1.githubusercontent.com/u/8375714 [HTTP/1.1 200 OK 614ms]
GET https://avatars3.githubusercontent.com/u/8321739 [HTTP/1.1 200 OK 41ms]
GET https://avatars1.githubusercontent.com/u/6986247 [HTTP/1.1 200 OK 82ms]
GET https://avatars3.githubusercontent.com/u/4426702 [HTTP/1.1 200 OK 637ms]
GET https://avatars3.githubusercontent.com/u/776526 [HTTP/1.1 200 OK 576ms]
GET https://avatars0.githubusercontent.com/u/8396662 [HTTP/1.1 200 OK 793ms]
GET https://avatars0.githubusercontent.com/u/3322532 [HTTP/1.1 200 OK 576ms]
GET https://avatars0.githubusercontent.com/u/10671676 [HTTP/1.1 200 OK 854ms]
GET https://avatars1.githubusercontent.com/u/1906689 [HTTP/1.1 200 OK 107ms]
GET https://avatars3.githubusercontent.com/u/4928548 [HTTP/1.1 200 OK 572ms]
GET https://avatars2.githubusercontent.com/u/8354609 [HTTP/1.1 200 OK 611ms]
GET https://github.com/WASdev/lib.rtcomm.clientjs/issues/new [HTTP/1.1 200 OK 82ms]
GET https://avatars3.githubusercontent.com/u/8375714 [HTTP/1.1 200 OK 291ms]
GET https://collector.githubapp.com/github/page_view [HTTP/1.1 200 OK 54ms]
GET https://www.google-analytics.com/collect [HTTP/1.1 200 OK 44ms]
POST https://www.google-analytics.com/collect [HTTP/1.1 200 OK 57ms]
POST https://github.com/_stats [HTTP/1.1 200 OK 51ms]
GET https://github.com/WASdev/lib.rtcomm.clientjs/suggestions/issue [HTTP/1.1 200 OK 207ms]

**Comment by swgraham** [comment]
Not sure what all of this is.  All of these calls to github seem weird.  In any case, I didn't mention you should 'build' the client using 'grunt lite'.  Try that before the test and let me know.

**Comment by nmolina09** [comment]
we tried grunt lite, and its not compiling right, here is the output:
File dist/rtcomm.js created.

Running "uglify:dist" (uglify) task
{ message: 'Unexpected token name «Object», expected punc «,»',
  line: 6,
  col: 20,
  pos: 258,
  stack: 'Error\n    at new JS_Parse_Error (/root/feb18/lib.rtcomm.clientjs/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:189:18)\n    at js_error (/root/feb18/lib.rtcomm.clientjs/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:197:11)\n    at croak (/root/feb18/lib.rtcomm.clientjs/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:661:41)\n    at token_error (/root/feb18/lib.rtcomm.clientjs/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:665:9)\n    at expect_token (/root/feb18/lib.rtcomm.clientjs/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:678:9)\n    at expect (/root/feb18/lib.rtcomm.clientjs/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:681:36)\n    at expr_list (/root/feb18/lib.rtcomm.clientjs/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:1173:44)\n    at /root/feb18/lib.rtcomm.clientjs/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:1188:23\n    at /root/feb18/lib.rtcomm.clientjs/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:704:24\n    at expr_atom (/root/feb18/lib.rtcomm.clientjs/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:1151:35)' }
>> Uglifying source dist/rtcomm.js failed.
Warning: Uglification failed.
Unexpected token name «Object», expected punc «,». 
Line 6 in dist/rtcomm.js
 Use --force to continue.
