### ISSUE TITLE
chat:message structure too deep

### ISSUE THREAD

**Issue by jediller** [WASdev/lib.rtcomm.clientjs#40]
The chat message callback object
ibmEndpointProvider.setRtcommEndpointConfig({
      webrtc: false,
      chat: true,
      broadcast: {audio: false, video: false},

      'chat:message': function(event_object) {

for example: event_object has a structure that is overly deep.
In a typical chat, the actual message sent by the other party would be accessed as:

event_object.message.message.message
-----
Further information: the complete callback:
 ibmEndpointProvider.setRtcommEndpointConfig({
      webrtc: false,
      chat: true,
      broadcast: {audio: false, video: false},

      'chat:message': function(event_object) {
         logarea("chat:message message from "+event_object.endpoint.getRemoteEndpointID());
         var messagereport = 'chat:message'
         for (var obj in event_object) messagereport += '\n'+obj + ': '+event_object[obj];
         logarea(messagereport);

         var messagereport2 = 'chat:message:deep'
         for (var obj in event_object.message) messagereport2 += '\n'+obj + ': '+event_object.message[obj];
         logarea(messagereport2);

         var messagereport3 = 'chat:message:deeper'
         for (var obj in event_object.message.message) messagereport3 += '\n'+obj + ': '+event_object.message.message[obj];
         logarea(messagereport3);

         document.getElementById('area1').value +=
            (new Date().stamp()+event_object.message.from+'           ').slice(0,28)+
            replaceAll(''+event_object.message.message,'\n','\n                           ');

         party(event_object.message.from);
      },

when invoked, provides ...

15-02-20 11:34:29 chat:message message from Norberto

15-02-20 11:34:29 chat:message
eventName: chat:message
endpoint: RtcommEndpoint[556045f9-471e-45da-c6c9-34ce231efff7]
message: [object Object]

15-02-20 11:34:29 chat:message:deep
message: [object Object]
from: Norberto

15-02-20 11:34:29 chat:message:deeper
message: Please work
from: Norberto
----------------
Another instance of where this callback is invoked by accepting a session ...

15-02-20 11:34:22 chat:message message from John

15-02-20 11:34:22 chat:message
eventName: chat:message
endpoint: RtcommEndpoint[af76970c-7d62-4a5a-8427-2aa1e5235ed0]
message: [object Object]

15-02-20 11:34:22 chat:message:deep
message: Accepting chat connection
from: John

15-02-20 11:34:22 chat:message:deeper
0: A
1: c
2: c
3: e
4: p
5: t
6: i
7: n
8: g
9:  
10: c
11: h
12: a
13: t
14:  
15: c
16: o
17: n
18: n
19: e
20: c
21: t
22: i
23: o
24: n

**Comment by swgraham** [comment]
John - I think this is fixed, it is still event_object.message.message which is two too deep, I'll look and see if that's correctable but I don't want to break anything of Brian's right now.  I'd suspect, since the build wasn't working due to that other issue, that you may have an older version of the client.

Let me know

**Comment by swgraham** [comment]
This is fixed
