### ISSUE TITLE
WebRTC:  Audio doesn't work for one party when using the Firefox browser

### ISSUE THREAD

**Issue by mkerr11** [WASdev/lib.rtcomm.clientjs#52]
When running a WebRTC Video Chat application, audio doesn't work for one of the two parties participating in the video chat using the Firefox browser.

Also encountered this issue when running a WebRTC AudioOnly application where the outbound endpoint was using a Firefox browser and the inbound endpoint was using a Chrome browser.

**Comment by swgraham** [comment]
This no longer occurs.
