### ISSUE TITLE
WebRTC Sample Video Chat Client has html syntax errors

### ISSUE THREAD

**Issue by mkerr11** [WASdev/lib.rtcomm.clientjs#53]
The WebRTC Sample Video Chat Client has html syntax errors which can be debugged if the videoClient.html is renamed to videoClient.xhtml since it is a stricter version of the HTML language.  When running the sample in Firefox, it found tags such as <br> and <input> without a closing tag for example.

**Comment by swgraham** [comment]
Made some changes in order to make the html compliant but it is not possible to make the same 'html' file both HTML and XHTML compliant.  

Closing this issue -- if an XHTML sample is necessary we can open an enhancement for that.
