### ISSUE TITLE
Ringing Continues Until All ICE Candidates Are Collected

### ISSUE THREAD

**Issue by jfmartinez** [WASdev/lib.rtcomm.clientjs#78]
While disabling trickleICE for SIP Trunking the ringing continued on endlessly due to the collection of ICE Candidates and up until the session:started even, this change will stop the ringing when the ICE Candidates start being collected (almost immediately after accepting the incoming session request).

This change also creates a new event for the WebRTCConnection - 'connecting' and for the RtcommEndpoint - 'session:connecting'.

**Comment by jfmartinez** [comment]
@swgraham I did a hotfix for this issue on the branch [issue-78](https://github.com/WASdev/lib.rtcomm.clientjs/tree/issue-78), but due to the changes you've made with the sub protocols I'm not sure where the correct way to stop the ringing on accept dialog would be. Any clue?

**Comment by swgraham** [comment]
@jfmartinez I just merged your work into develop w/ the subprotocol changes.  Can you pull it into your environment and do some testing w/ your apps before I push to master?  Thanks
